In [1]:
#SQL Basics Lab Exercise
import sqlite3
import pandas as pd

In [2]:
#1  Connect to (or create) the database file
conn = sqlite3.connect("sql_lab.db")
cursor = conn.cursor()
_ = cursor.execute("PRAGMA foreign_keys = ON;")

# --- Drop tables if they exist (for clean re-runs) ---
query = "DROP TABLE IF EXISTS Employees;"
_ = cursor.execute(query)

query = "DROP TABLE IF EXISTS Departments;"
_ = cursor.execute(query)

In [3]:
# 2. Create Departments Table

query = "DROP TABLE IF EXISTS Departments;"
_ = cursor.execute(query)

query = """
CREATE TABLE Departments (
    DepartmentID INTEGER PRIMARY KEY,
    DepartmentName VARCHAR(50),
    Location VARCHAR(50)
);
"""
_ = cursor.execute(query)
query = "PRAGMA table_info(Departments);"
display(pd.read_sql(query, conn))

   cid            name         type  notnull dflt_value  pk
0    0    DepartmentID      INTEGER        0       None   1
1    1  DepartmentName  VARCHAR(50)        0       None   0
2    2        Location  VARCHAR(50)        0       None   0

In [4]:
# # 3. --- Insert sample data into Departments ---
query = "DELETE FROM Departments;"
_ = cursor.execute(query)

query = """
INSERT INTO Departments (DepartmentID, DepartmentName, Location)
VALUES
(1, 'HR', 'London'),
(2, 'Finance', 'Frankfurt'),
(3, 'IT', 'Berlin'),
(4, 'Sales', 'Paris'),
(5, 'Marketing', 'Madrid');
"""
_ = cursor.execute(query)
query = "SELECT * FROM Departments"
display(pd.read_sql(query, conn))

   DepartmentID DepartmentName   Location
0             1             HR     London
1             2        Finance  Frankfurt
2             3             IT     Berlin
3             4          Sales      Paris
4             5      Marketing     Madrid

In [5]:
# 4 CREATE Employees Table

query = "DROP TABLE IF EXISTS Employees;"
_ = cursor.execute(query)

query = """
CREATE TABLE Employees (
 EmployeeID INTEGER PRIMARY KEY,
 FirstName VARCHAR(50),
 LastName VARCHAR(50),
 Gender VARCHAR(10),
 Age INTEGER,
 DepartmentID INTEGER,
 City VARCHAR(50),
 Salary INTEGER,
 FOREIGN KEY (DepartmentID) REFERENCES Departments(DepartmentID)
);
"""
_ = cursor.execute(query)
query = "SELECT * FROM Employees"
display(pd.read_sql(query,conn))

Empty DataFrame
Columns: [EmployeeID, FirstName, LastName, Gender, Age, DepartmentID, City, Salary]
Index: []

In [6]:
#  Insert Sample Employee Data 
query = "DELETE FROM Employees;"
_ = cursor.execute(query)

query = """
INSERT INTO Employees
(EmployeeID, FirstName, LastName, Gender, Age, DepartmentID, City, Salary)
VALUES
(101,'Emma','Wilson','Female',28,1,'London',45000),
(102,'Liam','Smith','Male',35,2,'Manchester',62000),
(103,'Sophia','Brown','Female',31,3,'Berlin',70000),
(104,'Noah','Taylor','Male',42,4,'Paris',68000),
(105,'Olivia','Martin','Female',26,5,'Madrid',48000),
(106,'Lucas','Muller','Male',38,3,'Munich',82000),
(107,'Isabella','Garcia','Female',30,2,'Barcelona',61000),
(108,'Ethan','Johnson','Male',45,1,'Dublin',75000),
(109,'Mia','Anderson','Female',27,4,'Amsterdam',52000),
(110,'James','Thomas','Male',33,3,'London',73000);
"""
_= cursor.execute(query)
query = "SELECT * FROM Employees"
display(pd.read_sql(query, conn))

,EmployeeID,FirstName,LastName,Gender,Age,DepartmentID,City,Salary
0,101,Emma,Wilson,Female,28,1,London,45000
1,102,Liam,Smith,Male,35,2,Manchester,62000
2,103,Sophia,Brown,Female,31,3,Berlin,70000
3,104,Noah,Taylor,Male,42,4,Paris,68000
4,105,Olivia,Martin,Female,26,5,Madrid,48000
5,106,Lucas,Muller,Male,38,3,Munich,82000
6,107,Isabella,Garcia,Female,30,2,Barcelona,61000
7,108,Ethan,Johnson,Male,45,1,Dublin,75000
8,109,Mia,Anderson,Female,27,4,Amsterdam,52000
9,110,James,Thomas,Male,33,3,London,73000

In [7]:
# Practice Quentions

# Understanding the Data

# 1. Display all employees
query = "SELECT * FROM Employees;"
display(pd.read_sql(query, conn))

,EmployeeID,FirstName,LastName,Gender,Age,DepartmentID,City,Salary
0,101,Emma,Wilson,Female,28,1,London,45000
1,102,Liam,Smith,Male,35,2,Manchester,62000
2,103,Sophia,Brown,Female,31,3,Berlin,70000
3,104,Noah,Taylor,Male,42,4,Paris,68000
4,105,Olivia,Martin,Female,26,5,Madrid,48000
5,106,Lucas,Muller,Male,38,3,Munich,82000
6,107,Isabella,Garcia,Female,30,2,Barcelona,61000
7,108,Ethan,Johnson,Male,45,1,Dublin,75000
8,109,Mia,Anderson,Female,27,4,Amsterdam,52000
9,110,James,Thomas,Male,33,3,London,73000

In [8]:
# 2. Display only the employee names and salaries
query = """
SELECT FirstName, LastName, Salary
FROM Employees;
"""
display(pd.read_sql(query, conn))

  FirstName  LastName  Salary
0      Emma    Wilson   45000
1      Liam     Smith   62000
2    Sophia     Brown   70000
3      Noah    Taylor   68000
4    Olivia    Martin   48000
5     Lucas    Muller   82000
6  Isabella    Garcia   61000
7     Ethan   Johnson   75000
8       Mia  Anderson   52000
9     James    Thomas   73000

In [9]:
# 3. Count the total number of employees
query = "SELECT COUNT(*) AS TotalEmployees FROM Employees;"
display(pd.read_sql(query, conn))

   TotalEmployees
0              10

In [10]:
# 4. Display all unique cities
query = "SELECT DISTINCT City FROM Employees;"
display(pd.read_sql(query, conn))

         City
0      London
1  Manchester
2      Berlin
3       Paris
4      Madrid
5      Munich
6   Barcelona
7      Dublin
8   Amsterdam

In [11]:
# 5. Display all unique department IDs
query = "SELECT DISTINCT DepartmentID FROM Employees;"
display(pd.read_sql(query, conn))

   DepartmentID
0             1
1             2
2             3
3             4
4             5

In [12]:
# TEST:  Display all unique department names From Departments
query = "SELECT DISTINCT DepartmentName FROM Departments;"
display(pd.read_sql(query, conn))

  DepartmentName
0             HR
1        Finance
2             IT
3          Sales
4      Marketing

In [13]:
# Filtering 
# 6. Find employees older than 30

query = "SELECT * FROM Employees WHERE Age > 30;"
display(pd.read_sql(query, conn))

,EmployeeID,FirstName,LastName,Gender,Age,DepartmentID,City,Salary
0,102,Liam,Smith,Male,35,2,Manchester,62000
1,103,Sophia,Brown,Female,31,3,Berlin,70000
2,104,Noah,Taylor,Male,42,4,Paris,68000
3,106,Lucas,Muller,Male,38,3,Munich,82000
4,108,Ethan,Johnson,Male,45,1,Dublin,75000
5,110,James,Thomas,Male,33,3,London,73000

In [14]:
# 7. Find employees earning more than 60,000
query = "SELECT * FROM Employees WHERE Salary > 60000;"
display(pd.read_sql(query, conn))

,EmployeeID,FirstName,LastName,Gender,Age,DepartmentID,City,Salary
0,102,Liam,Smith,Male,35,2,Manchester,62000
1,103,Sophia,Brown,Female,31,3,Berlin,70000
2,104,Noah,Taylor,Male,42,4,Paris,68000
3,106,Lucas,Muller,Male,38,3,Munich,82000
4,107,Isabella,Garcia,Female,30,2,Barcelona,61000
5,108,Ethan,Johnson,Male,45,1,Dublin,75000
6,110,James,Thomas,Male,33,3,London,73000

In [15]:
# 8. Display Employees from London
query = "SELECT * FROM Employees WHERE City =  'London'; "
display(pd.read_sql(query, conn))

   EmployeeID FirstName LastName  Gender  Age  DepartmentID    City  Salary
0         101      Emma   Wilson  Female   28             1  London   45000
1         110     James   Thomas    Male   33             3  London   73000

In [16]:
import os
print(os.getcwd())

/home/susmita/Susmita/Projects/Data_Engg/Lab_Works/Week1

In [17]:
# # 10. Display employees whose first name starts with L
query = "SELECT * FROM Employees WHERE FirstName LIKE 'L%';"
display(pd.read_sql(query, conn))

   EmployeeID FirstName LastName Gender  Age  DepartmentID        City  Salary
0         102      Liam    Smith   Male   35             2  Manchester   62000
1         106     Lucas   Muller   Male   38             3      Munich   82000

In [18]:
# 11. Display employees whose age is less than 35.

query = "SELECT * FROM Employees WHERE Age < 35; "
display(pd.read_sql(query, conn))

,EmployeeID,FirstName,LastName,Gender,Age,DepartmentID,City,Salary
0,101,Emma,Wilson,Female,28,1,London,45000
1,103,Sophia,Brown,Female,31,3,Berlin,70000
2,105,Olivia,Martin,Female,26,5,Madrid,48000
3,107,Isabella,Garcia,Female,30,2,Barcelona,61000
4,109,Mia,Anderson,Female,27,4,Amsterdam,52000
5,110,James,Thomas,Male,33,3,London,73000

In [19]:
# 9. Find employees whose salary is between 50,000 and 75,000
query = "SELECT * FROM Employees WHERE Salary BETWEEN 50000 AND 75000;"
display(pd.read_sql(query, conn))

,EmployeeID,FirstName,LastName,Gender,Age,DepartmentID,City,Salary
0,102,Liam,Smith,Male,35,2,Manchester,62000
1,103,Sophia,Brown,Female,31,3,Berlin,70000
2,104,Noah,Taylor,Male,42,4,Paris,68000
3,107,Isabella,Garcia,Female,30,2,Barcelona,61000
4,108,Ethan,Johnson,Male,45,1,Dublin,75000
5,109,Mia,Anderson,Female,27,4,Amsterdam,52000
6,110,James,Thomas,Male,33,3,London,73000

In [20]:
#  Sorting
    # 12. Sort employees by salary (highest first).

query = "SELECT * FROM Employees ORDER BY Salary DESC;"
display(pd.read_sql(query, conn))

,EmployeeID,FirstName,LastName,Gender,Age,DepartmentID,City,Salary
0,106,Lucas,Muller,Male,38,3,Munich,82000
1,108,Ethan,Johnson,Male,45,1,Dublin,75000
2,110,James,Thomas,Male,33,3,London,73000
3,103,Sophia,Brown,Female,31,3,Berlin,70000
4,104,Noah,Taylor,Male,42,4,Paris,68000
5,102,Liam,Smith,Male,35,2,Manchester,62000
6,107,Isabella,Garcia,Female,30,2,Barcelona,61000
7,109,Mia,Anderson,Female,27,4,Amsterdam,52000
8,105,Olivia,Martin,Female,26,5,Madrid,48000
9,101,Emma,Wilson,Female,28,1,London,45000

In [21]:
# 13. Sort employees by age (youngest first).

quesry = "SELECT * FROM Employees ORDER BY Age ASC;"
display (pd.read_sql(query, conn))

,EmployeeID,FirstName,LastName,Gender,Age,DepartmentID,City,Salary
0,106,Lucas,Muller,Male,38,3,Munich,82000
1,108,Ethan,Johnson,Male,45,1,Dublin,75000
2,110,James,Thomas,Male,33,3,London,73000
3,103,Sophia,Brown,Female,31,3,Berlin,70000
4,104,Noah,Taylor,Male,42,4,Paris,68000
5,102,Liam,Smith,Male,35,2,Manchester,62000
6,107,Isabella,Garcia,Female,30,2,Barcelona,61000
7,109,Mia,Anderson,Female,27,4,Amsterdam,52000
8,105,Olivia,Martin,Female,26,5,Madrid,48000
9,101,Emma,Wilson,Female,28,1,London,45000

In [22]:

# 14. Sort employees by city and then salary
query = "SELECT * FROM Employees ORDER BY City ASC, Salary ASC;"
display(pd.read_sql(query, conn))

,EmployeeID,FirstName,LastName,Gender,Age,DepartmentID,City,Salary
0,109,Mia,Anderson,Female,27,4,Amsterdam,52000
1,107,Isabella,Garcia,Female,30,2,Barcelona,61000
2,103,Sophia,Brown,Female,31,3,Berlin,70000
3,108,Ethan,Johnson,Male,45,1,Dublin,75000
4,101,Emma,Wilson,Female,28,1,London,45000
5,110,James,Thomas,Male,33,3,London,73000
6,105,Olivia,Martin,Female,26,5,Madrid,48000
7,102,Liam,Smith,Male,35,2,Manchester,62000
8,106,Lucas,Muller,Male,38,3,Munich,82000
9,104,Noah,Taylor,Male,42,4,Paris,68000

In [23]:
# Aggregate Function

# 15. Find the average salary
query = "SELECT AVG(Salary) AS AverageSalary FROM Employees;"
display(pd.read_sql(query, conn))

   AverageSalary
0        63600.0

In [24]:
# 16. Find the highest salary
query = "SELECT MAX(Salary) AS HighestSalary FROM Employees;"
display(pd.read_sql(query, conn))

   HighestSalary
0          82000

In [25]:
# 17. Find the minimum salary
query = "SELECT MIN(Salary) AS MinimumSalary FROM Employees;"
display(pd.read_sql(query, conn))

   MinimumSalary
0          45000

In [26]:
# 18. Find the average employee age
query = "SELECT AVG(Age) AS AverageAge FROM Employees;"
display(pd.read_sql(query, conn))

   AverageAge
0        33.5

In [27]:
# GROUP BY 
#19 Count Employees in each department

query = """
SELECT DepartmentID, COUNT(*) AS EmployeeCount
FROM Employees
GROUP BY DepartmentID;
"""
display(pd.read_sql(query, conn))

   DepartmentID  EmployeeCount
0             1              2
1             2              2
2             3              3
3             4              2
4             5              1

In [28]:
#  Find the average salary in each department.

query = """
SELECT DepartmentID, AVG(Salary) AS AverageSalary
FROM Employees
GROUP BY DEPARTMENTID;
"""
display(pd.read_sql(query, conn))

   DepartmentID  AverageSalary
0             1        60000.0
1             2        61500.0
2             3        75000.0
3             4        60000.0
4             5        48000.0

In [30]:
# 21. Find the highest salary in each department
query = """
SELECT DepartmentID, MAX(Salary) AS HighestSalary
FROM Employees
GROUP BY DepartmentID;
"""
display(pd.read_sql(query, conn))

   DepartmentID  HighestSalary
0             1          75000
1             2          62000
2             3          82000
3             4          68000
4             5          48000

In [29]:
# 22. Show only departments having more than one employee
query = """
SELECT DepartmentID, COUNT(*) AS EmployeeCount
FROM Employees
GROUP BY DepartmentID
HAVING COUNT(*) > 1;
"""
display(pd.read_sql(query, conn))

   DepartmentID  EmployeeCount
0             1              2
1             2              2
2             3              3
3             4              2

In [31]:
# UPDATA
# 23. Increase salaries of IT employees by 5%
query = """
UPDATE Employees
SET Salary = Salary * 1.05
WHERE DepartmentID = 3;
"""
_ = cursor.execute(query)
conn.commit()

query = "SELECT * FROM Employees WHERE DepartmentID = 3;"
display(pd.read_sql(query, conn))

   EmployeeID FirstName LastName  Gender  Age  DepartmentID    City  Salary
0         103    Sophia    Brown  Female   31             3  Berlin   73500
1         106     Lucas   Muller    Male   38             3  Munich   86100
2         110     James   Thomas    Male   33             3  London   76650

In [32]:
# 24. Change the city of EmployeeID 109 to Brussels
query = """
UPDATE Employees
SET City = 'Brussels'
WHERE EmployeeID = 109;
"""
_ = cursor.execute(query)
conn.commit()

query = "SELECT * FROM Employees WHERE EmployeeID = 109;"
display(pd.read_sql(query, conn))

   EmployeeID FirstName  LastName  Gender  Age  DepartmentID      City  Salary
0         109       Mia  Anderson  Female   27             4  Brussels   52000

In [33]:
#  DELETE Action

# 25. Delete employees whose salary is below 48,000

query = "DELETE FROM Employees WHERE Salary < 48000;"
_ = cursor.execute(query)
conn.commit()

query = "SELECT * FROM Employees;"
display(pd.read_sql(query, conn))

,EmployeeID,FirstName,LastName,Gender,Age,DepartmentID,City,Salary
0,102,Liam,Smith,Male,35,2,Manchester,62000
1,103,Sophia,Brown,Female,31,3,Berlin,73500
2,104,Noah,Taylor,Male,42,4,Paris,68000
3,105,Olivia,Martin,Female,26,5,Madrid,48000
4,106,Lucas,Muller,Male,38,3,Munich,86100
5,107,Isabella,Garcia,Female,30,2,Barcelona,61000
6,108,Ethan,Johnson,Male,45,1,Dublin,75000
7,109,Mia,Anderson,Female,27,4,Brussels,52000
8,110,James,Thomas,Male,33,3,London,76650

In [34]:
# JOIN Exercise

# 26. Display each employee along with their department name
query = """
SELECT e.FirstName, e.LastName, d.DepartmentName
FROM Employees e
JOIN Departments d ON e.DepartmentID = d.DepartmentID;
"""
display(pd.read_sql(query, conn))

  FirstName  LastName DepartmentName
0      Liam     Smith        Finance
1    Sophia     Brown             IT
2      Noah    Taylor          Sales
3    Olivia    Martin      Marketing
4     Lucas    Muller             IT
5  Isabella    Garcia        Finance
6     Ethan   Johnson             HR
7       Mia  Anderson          Sales
8     James    Thomas             IT

In [35]:
# 27. Display employee name, department name, and department location
query = """
SELECT e.FirstName, e.LastName, d.DepartmentName, d.Location
FROM Employees e
JOIN Departments d ON e.DepartmentID = d.DepartmentID;
"""
display(pd.read_sql(query, conn))

  FirstName  LastName DepartmentName   Location
0      Liam     Smith        Finance  Frankfurt
1    Sophia     Brown             IT     Berlin
2      Noah    Taylor          Sales      Paris
3    Olivia    Martin      Marketing     Madrid
4     Lucas    Muller             IT     Berlin
5  Isabella    Garcia        Finance  Frankfurt
6     Ethan   Johnson             HR     London
7       Mia  Anderson          Sales      Paris
8     James    Thomas             IT     Berlin

In [36]:
# 28. Count the number of employees in each department using a JOIN
query = """
SELECT d.DepartmentName, COUNT(e.EmployeeID) AS EmployeeCount
FROM Departments d
JOIN Employees e ON d.DepartmentID = e.DepartmentID
GROUP BY d.DepartmentName;
"""
display(pd.read_sql(query, conn))

  DepartmentName  EmployeeCount
0        Finance              2
1             HR              1
2             IT              3
3      Marketing              1
4          Sales              2

In [37]:
# 29. Display all departments, even if they have no employees
query = """
SELECT d.DepartmentName, e.FirstName, e.LastName
FROM Departments d
LEFT JOIN Employees e ON d.DepartmentID = e.DepartmentID;
"""
display(pd.read_sql(query, conn))

  DepartmentName FirstName  LastName
0             HR     Ethan   Johnson
1        Finance  Isabella    Garcia
2        Finance      Liam     Smith
3             IT     James    Thomas
4             IT     Lucas    Muller
5             IT    Sophia     Brown
6          Sales       Mia  Anderson
7          Sales      Noah    Taylor
8      Marketing    Olivia    Martin

In [38]:
# 30. Find the average salary for each department using a JOIN
query = """
SELECT d.DepartmentName, AVG(e.Salary) AS AverageSalary
FROM Departments d
JOIN Employees e ON d.DepartmentID = e.DepartmentID
GROUP BY d.DepartmentName;
"""
display(pd.read_sql(query, conn))

  DepartmentName  AverageSalary
0        Finance        61500.0
1             HR        75000.0
2             IT        78750.0
3      Marketing        48000.0
4          Sales        60000.0

In [39]:
# 31. Display employees who work in departments located in Berlin
query = """
SELECT e.FirstName, e.LastName, d.Location
FROM Employees e
JOIN Departments d ON e.DepartmentID = d.DepartmentID
WHERE d.Location = 'Berlin';
"""
display(pd.read_sql(query, conn))

  FirstName LastName Location
0    Sophia    Brown   Berlin
1     Lucas   Muller   Berlin
2     James   Thomas   Berlin

In [40]:
# 32. Display only employees working in the IT department (using a JOIN instead of filtering by ID)
query = """
SELECT e.FirstName, e.LastName, d.DepartmentName
FROM Employees e
JOIN Departments d ON e.DepartmentID = d.DepartmentID
WHERE d.DepartmentName = 'IT';
"""
display(pd.read_sql(query, conn))

  FirstName LastName DepartmentName
0    Sophia    Brown             IT
1     Lucas   Muller             IT
2     James   Thomas             IT

In [41]:
# BONUS Challenges
# 33. Display the Top 3 highest-paid employees
query = """
SELECT FirstName, LastName, Salary
FROM Employees
ORDER BY Salary DESC
LIMIT 3;
"""
display(pd.read_sql(query, conn))

  FirstName LastName  Salary
0     Lucas   Muller   86100
1     James   Thomas   76650
2     Ethan  Johnson   75000

In [42]:
# 34. Find employees whose salary is above the company average
query = """
SELECT FirstName, LastName, Salary
FROM Employees
WHERE Salary > (SELECT AVG(Salary) FROM Employees);
"""
display(pd.read_sql(query, conn))

  FirstName LastName  Salary
0    Sophia    Brown   73500
1      Noah   Taylor   68000
2     Lucas   Muller   86100
3     Ethan  Johnson   75000
4     James   Thomas   76650

In [43]:
# 35. Find the department with the highest average salary
query = """
SELECT d.DepartmentName, AVG(e.Salary) AS AverageSalary
FROM Departments d
JOIN Employees e ON d.DepartmentID = e.DepartmentID
GROUP BY d.DepartmentName
ORDER BY AverageSalary DESC
LIMIT 1;
"""
display(pd.read_sql(query, conn))

  DepartmentName  AverageSalary
0             IT        78750.0

In [44]:
# 36. Display the oldest employee in each department
query = """
SELECT DepartmentID, FirstName, LastName, Age
FROM Employees e1
WHERE Age = (
    SELECT MAX(Age)
    FROM Employees e2
    WHERE e2.DepartmentID = e1.DepartmentID
);
"""
display(pd.read_sql(query, conn))

   DepartmentID FirstName LastName  Age
0             2      Liam    Smith   35
1             4      Noah   Taylor   42
2             5    Olivia   Martin   26
3             3     Lucas   Muller   38
4             1     Ethan  Johnson   45

In [45]:
# 37. Display employees whose last name contains the letter 'o'
query = """
SELECT FirstName, LastName
FROM Employees
WHERE LastName LIKE '%o%';
"""
display(pd.read_sql(query, conn))

  FirstName  LastName
0    Sophia     Brown
1      Noah    Taylor
2     Ethan   Johnson
3       Mia  Anderson
4     James    Thomas

In [46]:
# 38. Show the total salary paid by each department
query = """
SELECT d.DepartmentName, SUM(e.Salary) AS TotalSalary
FROM Departments d
JOIN Employees e ON d.DepartmentID = e.DepartmentID
GROUP BY d.DepartmentName;
"""
display(pd.read_sql(query, conn))

  DepartmentName  TotalSalary
0        Finance       123000
1             HR        75000
2             IT       236250
3      Marketing        48000
4          Sales       120000

In [47]:
# 39. Display employees earning the second-highest salary
query = """
SELECT FirstName, LastName, Salary
FROM Employees
ORDER BY Salary DESC
LIMIT 1 OFFSET 1;
"""
display(pd.read_sql(query, conn))

  FirstName LastName  Salary
0     James   Thomas   76650

In [48]:
# 40. Find the city with the highest number of employees
query = """
SELECT City, COUNT(*) AS EmployeeCount
FROM Employees
GROUP BY City
ORDER BY EmployeeCount DESC
LIMIT 1;
"""
display(pd.read_sql(query, conn))

    City  EmployeeCount
0  Paris              1